apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-01-03T05:17:29Z"
    generateName: plugin-aws-ec2-inven-collector-rrzecgirtquoetbl-5c75566dc5-
    generation: 1
    labels:
      domain_id: domain-af00a9336108
      plugin_id: plugin-aws-ec2-inven-collector
      pod-template-hash: 5c75566dc5
      resource_type: inventory.Collector
      supervisor_name: root
      version: 1.0.36
    name: plugin-aws-ec2-inven-collector-rrzecgirtquoetbl-5c75566dc59t8qc
    namespace: cloudforet-plugin
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: plugin-aws-ec2-inven-collector-rrzecgirtquoetbl-5c75566dc5
      uid: b6ed0e6d-91d6-4ae0-b450-81792c37f24f
    resourceVersion: "8089"
    uid: 4b8f82a5-9e91-4b41-984a-249d569b4408
  spec:
    containers:
    - image: registry.hub.docker.com/cloudforet/plugin-aws-inven-collector:1.0.36
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        tcpSocket:
          port: 50051
        timeoutSeconds: 1
      name: plugin-aws-ec2-inven-collector-rrzecgirtquoetbl
      ports:
      - containerPort: 50051
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-tmr9n
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: k3s-server
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-tmr9n
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-01-03T05:17:55Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-01-03T05:17:29Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-01-03T05:17:55Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-01-03T05:17:55Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-01-03T05:17:29Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://29701a58ae537c9e9a3361571d0187e0de0c69dd31554a7204cb49e60cf4d464
      image: registry.hub.docker.com/cloudforet/plugin-aws-inven-collector:1.0.36
      imageID: registry.hub.docker.com/cloudforet/plugin-aws-inven-collector@sha256:3777cefb90237bda62653a71f80309595c163817217934663f63df4a7fcef64f
      lastState: {}
      name: plugin-aws-ec2-inven-collector-rrzecgirtquoetbl
      ready: true
      resources: {}
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-01-03T05:17:55Z"
      user:
        linux:
          gid: 0
          supplementalGroups:
          - 0
          uid: 0
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-tmr9n
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 172.18.0.2
    hostIPs:
    - ip: 172.18.0.2
    observedGeneration: 1
    phase: Running
    podIP: 10.42.0.167
    podIPs:
    - ip: 10.42.0.167
    qosClass: BestEffort
    startTime: "2026-01-03T05:17:29Z"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      spaceone.supervisor.domain_id: domain-af00a9336108
      spaceone.supervisor.name: root
      spaceone.supervisor.plugin.endpoint: grpc://plugin-aws-ec2-inven-collector-rrzecgirtquoetbl.supervisor.svc.cluster.local:50051
      spaceone.supervisor.plugin.image: cloudforet/plugin-aws-inven-collector
      spaceone.supervisor.plugin.resource_type: inventory.Collector
      spaceone.supervisor.plugin.version: 1.0.36
      spaceone.supervisor.plugin_id: plugin-aws-ec2-inven-collector
    creationTimestamp: "2026-01-03T05:17:29Z"
    labels:
      domain_id: domain-af00a9336108
      plugin_id: plugin-aws-ec2-inven-collector
      resource_type: inventory.Collector
      supervisor_name: root
      version: 1.0.36
    name: plugin-aws-ec2-inven-collector-rrzecgirtquoetbl
    namespace: cloudforet-plugin
    resourceVersion: "8061"
    uid: fb87dc3a-7ae3-441f-9308-83c0c719cf0c
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
    selector:
      domain_id: domain-af00a9336108
      plugin_id: plugin-aws-ec2-inven-collector
      resource_type: inventory.Collector
      supervisor_name: root
      version: 1.0.36
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2026-01-03T05:17:29Z"
    generation: 1
    labels:
      domain_id: domain-af00a9336108
      plugin_id: plugin-aws-ec2-inven-collector
      resource_type: inventory.Collector
      supervisor_name: root
      version: 1.0.36
    name: plugin-aws-ec2-inven-collector-rrzecgirtquoetbl
    namespace: cloudforet-plugin
    resourceVersion: "8093"
    uid: ece87d61-cbaf-4c1d-976f-35e7c2b5da43
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        domain_id: domain-af00a9336108
        plugin_id: plugin-aws-ec2-inven-collector
        resource_type: inventory.Collector
        supervisor_name: root
        version: 1.0.36
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          domain_id: domain-af00a9336108
          plugin_id: plugin-aws-ec2-inven-collector
          resource_type: inventory.Collector
          supervisor_name: root
          version: 1.0.36
        name: plugin-aws-ec2-inven-collector-rrzecgirtquoetbl
      spec:
        containers:
        - image: registry.hub.docker.com/cloudforet/plugin-aws-inven-collector:1.0.36
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 50051
            timeoutSeconds: 1
          name: plugin-aws-ec2-inven-collector-rrzecgirtquoetbl
          ports:
          - containerPort: 50051
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-01-03T05:17:55Z"
      lastUpdateTime: "2026-01-03T05:17:55Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2026-01-03T05:17:29Z"
      lastUpdateTime: "2026-01-03T05:17:55Z"
      message: ReplicaSet "plugin-aws-ec2-inven-collector-rrzecgirtquoetbl-5c75566dc5"
        has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2026-01-03T05:17:29Z"
    generation: 1
    labels:
      domain_id: domain-af00a9336108
      plugin_id: plugin-aws-ec2-inven-collector
      pod-template-hash: 5c75566dc5
      resource_type: inventory.Collector
      supervisor_name: root
      version: 1.0.36
    name: plugin-aws-ec2-inven-collector-rrzecgirtquoetbl-5c75566dc5
    namespace: cloudforet-plugin
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: plugin-aws-ec2-inven-collector-rrzecgirtquoetbl
      uid: ece87d61-cbaf-4c1d-976f-35e7c2b5da43
    resourceVersion: "8091"
    uid: b6ed0e6d-91d6-4ae0-b450-81792c37f24f
  spec:
    replicas: 1
    selector:
      matchLabels:
        domain_id: domain-af00a9336108
        plugin_id: plugin-aws-ec2-inven-collector
        pod-template-hash: 5c75566dc5
        resource_type: inventory.Collector
        supervisor_name: root
        version: 1.0.36
    template:
      metadata:
        labels:
          domain_id: domain-af00a9336108
          plugin_id: plugin-aws-ec2-inven-collector
          pod-template-hash: 5c75566dc5
          resource_type: inventory.Collector
          supervisor_name: root
          version: 1.0.36
        name: plugin-aws-ec2-inven-collector-rrzecgirtquoetbl
      spec:
        containers:
        - image: registry.hub.docker.com/cloudforet/plugin-aws-inven-collector:1.0.36
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 50051
            timeoutSeconds: 1
          name: plugin-aws-ec2-inven-collector-rrzecgirtquoetbl
          ports:
          - containerPort: 50051
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
